/**
 * Generates src/ui-embed.ts with import statements for all files in ui/build/.
 * Each file is imported with { type: "file" } so Bun embeds it in the compiled binary.
 * The generated module exports a Map<urlPath, bunfsPath> for serving at runtime.
 */
import { readdirSync, statSync, writeFileSync } from "fs";
import { join, relative } from "path";

const BUILD_DIR = join(import.meta.dir, "..", "ui", "build");
const OUT_FILE = join(import.meta.dir, "..", "src", "ui-embed.ts");

function walk(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      results.push(...walk(full));
    } else {
      results.push(full);
    }
  }
  return results;
}

const files = walk(BUILD_DIR);
const imports: string[] = [];
const mapEntries: string[] = [];

for (let i = 0; i < files.length; i++) {
  const rel = relative(BUILD_DIR, files[i]); // e.g. "_app/immutable/chunks/foo.js"
  const urlPath = "/" + rel;
  const importPath = "../ui/build/" + rel;
  const varName = `f${i}`;

  imports.push(`import ${varName} from ${JSON.stringify(importPath)} with { type: "file" };`);
  mapEntries.push(`  [${JSON.stringify(urlPath)}, ${varName}],`);
}

const code = `// Auto-generated by scripts/embed-ui.ts -- do not edit
${imports.join("\n")}

export const EMBEDDED_UI = new Map<string, string>([\n${mapEntries.join("\n")}\n]);\n`;

writeFileSync(OUT_FILE, code);
console.log(`Embedded ${files.length} UI files into src/ui-embed.ts`);
